blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://discord.gg/EsNDvBaHVU
    about: Please ask questions in the Aliucord Discord server instead of opening an issue here.